### ISSUE TITLE
README improvement : add screenshot

### ISSUE THREAD

**Issue by nathmo** [Proxtx/nginx-config-gui#1]
hi there, you're project looks really nice but it's hard know how to looks like and works withouth testing it as there is no screenshot.
would you ming adding a few screenshot of your plugins in action.

also I guess a significant part of the people interested by your project are people like me who are not comfortable with nginx and hoped that your plugin could provide an easy interface to manage the config. To do so i would recommand having a more detailled setup guide from scratch (step for a mininal nginx install and a list of command to copy past step by step + what to look for after each command)

**Comment by Proxtx** [comment]
hey I updated the readme to include a demo video. I also added quick install instructions. I can't really provide install guide on nginx since it's different for every system.
